version: "3.2"
services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,lambda,cloudformation,sqs,s3
      - DEFAULT_REGION=eu-west-1
      - START_WEB=false
    volumes:
      - "C:/Users/P3720090/Desktop/Docker/imagedemo/localstack/dynamodb-tables:/tmp/dynamodb-tables"
      - "C:/Users/P3720090/Desktop/Docker/imagedemo/localstack/init.d:/docker-entrypoint-initaws.d"
  imagedemo:
    build: .
    depends_on:
      - localstack
    restart: on-failure
    ports:
      - 8081:8080
    volumes:
      - "C:/Users/P3720090/Desktop/Docker/imagedemo/logs:/logs"